### ISSUE TITLE
Add user command to display the last ddg created (if any)

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#128]
If it turns out that users have difficulty finding the jar file for DDG Explorer, we might add a user command that would display the last DDG created, if any.  For example:

ddg.display.ddg <- function () {
  if (.ddg.is.set("ddg.path")) {
    .ddg.loadDDG(.ddg.path())
  } else {
    print("No ddg path is set")
  }
}

**Comment by MKLau** [comment]
I like this idea. In general, I like the idea of moving away from clicking through the file system, which is what the majority of users are doing outside of R.

On Jul 6, 2016, at 5:02 PM, erboose <notifications@github.com<mailto:notifications@github.com>> wrote:


If it turns out that users have difficulty finding the jar file for DDG Explorer, we might add a user command that would display the last DDG created, if any. For example:

ddg.display.ddg <- function () {
if (.ddg.is.set("ddg.path")) {
.ddg.loadDDG(.ddg.path())
} else {
print("No ddg path is set")
}
}

**Comment by erboose** [comment]
This turns out to be quite useful since you don't have to find either the jar file or ddg.txt for the last DDG created with ddg.run.  Here's a better version:

ddg.display.ddg <- function () {
  if (.ddg.is.set("ddg.path") & file.exists(paste(.ddg.path(), "/ddg.txt", sep=""))) {
    .ddg.loadDDG(.ddg.path())
  } else {
    print("DDG not available")
  }
}

**Comment by blernermhc** [comment]
Looks good.  You should add that to development.

**Comment by erboose** [comment]
Implemented.
