### ISSUE TITLE
RDataTracker launched DDG explorer in foreground

### ISSUE THREAD

**Issue by margoseltzer** [End-to-end-provenance/RDataTracker#141]
It was a real problem for users at the tutorial (as well as for me) that once you display the DDG, you can't do anything in R.  I think that if we simply put an "&" at the end of the command line that we generate in the "system" call to launch DDG explorer, this will take care of the problem.

**Comment by blernermhc** [comment]
Moe's code to do the incremental drawing will not have this problem.  It's close...

**Comment by margoseltzer** [comment]
But we’re not going to require that users have to do incremental drawing are we?

- M

**Comment by blernermhc** [comment]
Right, but the same mechanism will be used to start DDG Explorer in both cases.

**Comment by tfjmp** [comment]
How is DDG-Explorer going to be started? I though R would `exec` DDG-Explorer and we would pass a parameters for DDG-Explorer to either read from files or listen on a pipe/socket connected to RDataTracker. 

If there is a different way to `exec` DDG-Explorer than doing calling `system`, we may as well update that code right now.

**Comment by blernermhc** [comment]
I don't have Moe's code.  The basic idea is that RDataTracker will start DDG Explorer (if it is not already running) and create a socket to talk to it.  It will continue to run after a script completes, so if the user runs and displays a second script, it will show up in a second tab instead of starting DDG Explorer all over.

It requires changes on both the RDataTracker and DDG Explorer sides to get this working.

**Comment by tfjmp** [comment]
Pull request #142 should fix this.
