### ISSUE TITLE
Separate regression tests into another repo?

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#144]

**Comment by blernermhc** [comment]
It's not clear to me what the advantage is of having the regression tests in a separate repository.  With them in the same repository, it would mean that anybody who cloned RDatatTracker would get the regression tests, too, which seems like a good idea since somebody who clones the repository may want to contribute to its development.

They are not included in the install file that we build for R or included if somebody does install_github, so the standard R programmer would not see them.

**Comment by tfjmp** [comment]
You can easily git clone the regression test in the build script tough.

**Comment by MKLau** [comment]
A good reason that I see for separating the regression tests from the RDT repo is that we might be making changes to the regression tests separately from RDT. This could (and I think probably would) lead to a situation in which we want to make the regression tests available to everyone working on the project but not have to update the development or master branches. 

Along the tack of Thomas' comment, we can add information to the contribution section of the dev wiki. If we add the regression test repo to the RDT .gitignore file, then contributors could place the regression tests anywhere they want.

**Comment by blernermhc** [comment]
The way that the regression tests work is that for each test case, we save correct ddgs and correct standard output in files called "expected..".  Then, when we run the regression tests, the new results are compared to the expected results.

As features change or bugs or fixed, what is considered correct can change.  I think keeping the regression tests with the R code would ensure that the expected results were consistent with the code.  I think it would be hard to do that otherwise.

In the past, regression tests themselves (as opposed to the results) change when we add a new feature so that the new feature gets tested, or add a test case to test a new bug fix.  This again suggests that associating the tests with code branches is reasonable.

**Comment by tfjmp** [comment]
This would be a typical use case for tagging releases.

i.e. when a certain version of RDataTracker is released the correct regression test is tagged beforehand, and the script of the RDataTracker release pull that particular version from the repo.

**Comment by blernermhc** [comment]
I think we would want finer granularity than just when we make a release.  As soon as we add a feature, we will want regression tests for that feature, but those tests will only work on branches of RDataTracker that contain the feature.  I think there really is a tight binding between regression test expected results and the branch of code being tested, and I think that tight binding is appropriate.

There are other things we could move out of the repo into a different "extras" repository:  ScientistScripts, examples, and test.xml.  Then, we could rename examples-no-instrumentation to "tests" or "regression-tests" and rename the script "test-no-instrumentation.xml" to "test.xml" or "regression-test.xml".

**Comment by erboose** [comment]
I agree on both counts: the RDT code and regression tests are best kept together and it would be helpful to streamline the tests and move non-essential items to a separate repository.

**Comment by MKLau** [comment]
Emery and I are working on cleaning up the RDataTracker repo files, per Monday's discussion. 

Regarding the discussion of keeping the regression testing, those files will be kept in the repo. 

Closing this issue and opening a new issue.
