### ISSUE TITLE
S4 Class Deprecation warning

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#165]
I get the following when I run a script (details below) using the development branch (on both End-to-end-provenance or Thomas's fork of the repo).

n [<-(*tmp*, next.cmd, value = ) :

implicit list embedding of S4 objects is deprecated

The script is in dev/src/eepOdy/src/eepOdy.R.

**Comment by blernermhc** [comment]
When I try to run this without RDataTracker, I get the error:

Error: could not find function "qmap"

Where is qmap defined?

**Comment by MKLau** [comment]
Sorry, qmap is a function for making a map. You can comment out all of the lines for making the map, i.e. qmap and lower.

On Oct 6, 2016, at 6:04 PM, blernermhc <notifications@github.com<mailto:notifications@github.com>> wrote:


When I try to run this without RDataTracker, I get the error:

Error: could not find function "qmap"

Where is qmap defined?

-

**Comment by MKLau** [comment]
Just added an install check and library section to the script. It should run without errors now.

**Comment by blernermhc** [comment]
This new version runs for me with no errors and creates a DDG.  Can you send the ddg that you get?

**Comment by blernermhc** [comment]
Also, does the script work correctly if you are not using RDataTracker?

**Comment by MKLau** [comment]
The ddg that I produce should already be in the repo in the eepOdy_ddg folder. The script runs for me with RDataTracker and without it. I can view the ddg with CamFlow just fine.

**Comment by blernermhc** [comment]
Ok, I can load the ddg.txt that you produced fine in DDG Explorer.  I am confused.  When is the error that you reported coming out?

**Comment by MKLau** [comment]
It's a warning. The ddg is produced but if you run warnings() it returns the message multiple times.

On Oct 6, 2016, at 9:18 PM, blernermhc <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I can load the ddg.txt that you produced fine in DDG Explorer. I am confused. When is the error that you reported coming out?

-

**Comment by blernermhc** [comment]
The only warning I see is:

package ‘ggplot2’ was built under R version 3.2.4

**Comment by erboose** [comment]
Any chance that you have different versions of R?

Sent from my iPhone

On Oct 7, 2016, at 8:39 AM, blernermhc <notifications@github.com<mailto:notifications@github.com>> wrote:


The only warning I see is:

package 'ggplot2' was built under R version 3.2.4

-

**Comment by tfjmp** [comment]
I had the same warning as Matt. Both on Linux and Windows.

**Comment by blernermhc** [comment]
What version of R are you using?  I have 3.2.3.

**Comment by tfjmp** [comment]
Version in 3.3.1, the current version...

**Comment by tfjmp** [comment]
```
Warning messages:
1: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
2: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
3: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
4: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
5: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
6: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
7: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
8: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
9: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
10: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
11: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
12: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
13: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
14: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
15: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
16: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
17: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
18: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
19: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
20: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
21: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
22: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
23: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
24: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
25: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
26: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
27: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
28: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
29: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
30: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
31: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
32: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
33: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
34: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
35: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
```

**Comment by MKLau** [comment]
Yeah, I also have 3.3.1.

Barb, I think that CRAN had been working on changes to the S4 data class. It's possible that a tenths place update would have an impact. I'll do a little searching on S4 updates.

On Oct 7, 2016, at 10:23 AM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com>> wrote:


Warning messages:
1: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
2: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
3: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
4: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
5: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
6: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
7: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
8: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
9: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
10: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
11: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
12: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
13: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
14: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
15: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
16: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
17: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
18: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
19: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
20: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
21: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
22: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
23: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
24: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
25: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
26: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
27: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
28: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
29: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
30: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
31: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
32: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
33: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
34: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated
35: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
  implicit list embedding of S4 objects is deprecated


-

**Comment by erboose** [comment]
If it turns out that S4 objects are a problem we might be able to manage the same information directly through lists.

Sent from my iPhone

On Oct 7, 2016, at 11:04 AM, MKLau <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah, I also have 3.3.1.

Barb, I think that CRAN had been working on changes to the S4 data class. It's possible that a tenths place update would have an impact. I'll do a little searching on S4 updates.

On Oct 7, 2016, at 10:23 AM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Warning messages:
1: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
2: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
3: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
4: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
5: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
6: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
7: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
8: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
9: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
10: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
11: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
12: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
13: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
14: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
15: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
16: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
17: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
18: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
19: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
20: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
21: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
22: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
23: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
24: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
25: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
26: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
27: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
28: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
29: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
30: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
31: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
32: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
33: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
34: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
35: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated


-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_End-2Dto-2Dend-2Dprovenance_RDataTracker_issues_165-23issuecomment-2D252265749&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=nVXc4b9o7QJ-bo7s3xVT9P81b4JtJ5F43FObNCtxY9s&s=wCEpTMA1_FnO0qL5z_5A0iAFTQDb7q6Bzq0l9--m4os&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFGGib-5FONOMgtDpj7W1DF60ZEePdWQ-5F9ks5qxlXfgaJpZM4KQcZv&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=nVXc4b9o7QJ-bo7s3xVT9P81b4JtJ5F43FObNCtxY9s&s=mULuZsGCe84Fy32j4b7GMLjsjeEjb7bDKxKS5Q9D7Xw&e=>.

-

**Comment by MKLau** [comment]
I just did a quick search of S4 class updates in the last two years of the R Journal, and found something similar.

This was in the last series of updates:

[<- with an S4 value into a list currently embeds the S4 object into
 its own list such that the end result is roughly equivalent to using
 [[<-. That behavior is deprecated.  In the future, the S4 value will
 be coerced to a list with as.list().



On Oct 7, 2016, at 11:42 AM, erboose <notifications@github.com<mailto:notifications@github.com>> wrote:

If it turns out that S4 objects are a problem we might be able to manage the same information directly through lists.

Sent from my iPhone

On Oct 7, 2016, at 11:04 AM, MKLau <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Yeah, I also have 3.3.1.

Barb, I think that CRAN had been working on changes to the S4 data class. It's possible that a tenths place update would have an impact. I'll do a little searching on S4 updates.

On Oct 7, 2016, at 10:23 AM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Warning messages:
1: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
2: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
3: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
4: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
5: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
6: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
7: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
8: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
9: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
10: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
11: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
12: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
13: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
14: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
15: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
16: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
17: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
18: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
19: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
20: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
21: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
22: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
23: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
24: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
25: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
26: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
27: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
28: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
29: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
30: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
31: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
32: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
33: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
34: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated
35: In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :
implicit list embedding of S4 objects is deprecated


-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_End-2Dto-2Dend-2Dprovenance_RDataTracker_issues_165-23issuecomment-2D252265749&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=nVXc4b9o7QJ-bo7s3xVT9P81b4JtJ5F43FObNCtxY9s&s=wCEpTMA1_FnO0qL5z_5A0iAFTQDb7q6Bzq0l9--m4os&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFGGib-5FONOMgtDpj7W1DF60ZEePdWQ-5F9ks5qxlXfgaJpZM4KQcZv&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=nVXc4b9o7QJ-bo7s3xVT9P81b4JtJ5F43FObNCtxY9s&s=mULuZsGCe84Fy32j4b7GMLjsjeEjb7bDKxKS5Q9D7Xw&e=>.

-

**Comment by blernermhc** [comment]
I upgraded my version of R and see the warning as well now.

**Comment by blernermhc** [comment]
Ok, it has nothing to do with your script and has entirely to do with R 3.3.1.  I will investigate what the approved way of creating a list of S4 objects is.

**Comment by MKLau** [comment]
Great, thanks Barb!

By the way, this is a great example of a use case. Can you or Emery tell what part of RDataTracker is causing this or, more specifically, can you isolate code that will replicate this?



On Oct 7, 2016, at 3:47 PM, blernermhc <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, it has nothing to do with your script and has entirely to do with R 3.3.1. I will investigate what the approved way of creating a list of S4 objects is.

**Comment by blernermhc** [comment]
It failed with any R script before it even started executing the script.

I just created a pull request to fix it, which required just changing 2 lines of code.

**Comment by MKLau** [comment]
Ok, looks pretty simple. It looks like it's just that an assignment to an object with a single bracket is now deprecated and so they're giving us a warning message.

**Comment by blernermhc** [comment]
Fixed in [https://github.com/End-to-end-provenance/RDataTracker/commit/6897e437b04b3f632834b0fc6ad59a6e2f9c4937](https://github.com/End-to-end-provenance/RDataTracker/commit/6897e437b04b3f632834b0fc6ad59a6e2f9c4937)
