### ISSUE TITLE
DDG is not linked correctly when `<<-` is used

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#189]
**Original problem:**
When `<<-` is used, it automatically assumes that the evironment is `R_GlobalEnv`. This is incorrect.

**Progress 1:**
The function which assumes the environment is global, `.ddg.is.global.assign(...)` has been changed to `.ddg.is.nonlocal.assign(...)`.
In the 2 locations which this function is called, `.ddg.where(...)` is called to find the correct environment.

**Progress 2:**
In the following simple case:
```
fn <- function()
{
    a <<- 3
}

fn()
d <- a
```
By printing out the data table, `ddg.data.nodes`, whenever a new data node is added to the table using `.ddg.set( "ddg.data.nodes" , ddg.data.nodes )`, it is found that the scope for `a` is incorrect. 
It should be `R_GlobalEnv`, but another environment was recorded instead.

**Progress 3:**
By tracking the function calls made which lead to `.ddg.set( "ddg.data.nodes" , ddg.data.nodes )` and the functions which call `.ddg.is.nonlocal.assign(...)`, we determined that `.ddg.save.data(...)` and `.ddg.get.scope(...)` have been given the wrong value for some of their parameters.

In the following case:
```
fn <- function()
{
    a <<- 3
    b <- 5
}

fn()
d <- a
```
It has been found that the DDG is correct when `a <<-3` is not the last line of the function.
Therefore, in the 2 methods where `.ddg.is.nonlocal.assign(...)` is called, `.ddg.parse.commands(...)` and `ddg.return.value(...)`, the bug lies in `ddg.return.value(...)` as it is the function called when `a <<- 3` is the last line of the function.

**Comment by erboose** [comment]
For troubleshooting, note that if save.debug=TRUE in ddg.run, a copy of the annotated script that is executed is saved in the debug directory. Statements inside functions are wrapped with ddg.eval (unless they are ddg functions), except for the last statement, which is wrapped with ddg.return.value, unless it's a return statement, in which case the argument of the return statement is wrapped with ddg.return.value.

Sent from my iPhone

On Dec 7, 2016, at 3:25 PM, Elizabeth Fong <notifications@github.com<mailto:notifications@github.com>> wrote:


Original problem:
When <<- is used, it automatically assumes that the evironment is R_GlobalEnv. This is incorrect.

Progress 1:
The function which assumes the environment is global, .ddg.is.global.assign(...) has been changed to .ddg.is.nonlocal.assign(...).
In the 2 locations which this function is called, .ddg.where(...) is called to find the correct environment.

Progress 2:
In the following simple case:

fn <- function()
{
    a <<- 3
}

fn()
d <- a


By printing out the data table, ddg.data.nodes, whenever a new data node is added to the table using .ddg.set( "ddg.data.nodes" , ddg.data.nodes ), it is found that the scope for a is incorrect.
It should be R_GlobalEnv, but another environment was recorded instead.

Progress 3:
By tracking the function calls made which lead to .ddg.set( "ddg.data.nodes" , ddg.data.nodes ) and the functions which call .ddg.is.nonlocal.assign(...), we determined that .ddg.save.data(...) and .ddg.get.scope(...) have been given the wrong value for some of their parameters.

In the following case:

fn <- function()
{
    a <<- 3
    b <- 5
}

fn()
d <- a


It has been found that the DDG is correct when a <<-3 is not the last line of the function.
Therefore, in the 2 methods where .ddg.is.nonlocal.assign(...) is called, .ddg.parse.commands(...) and ddg.return.value(...), the bug lies in ddg.return.value(...) as it is the function called when a <<- 3 is the last line of the function.

-

**Comment by fong22e** [comment]
That really helps! Thank you so much, Emery!

**Comment by fong22e** [comment]
__Progress 4:__  
I believe it has now been fixed! The issue was that the expression passed into `.ddg.is.nonlocal.assign()`, previously `.ddg.is.global.assign()`, was in it's wrapped, unparsed state. Once the actual expression has been extracted from the parse tree, expressions containing `<<-` will return true when passed into `.ddg.is.nonlocal.assign()` as it is then recognised as a call. The unparsed version is not recognised as a call.

**Comment by fong22e** [comment]
__Progress 5:__
Unfortunately, I just found another bug in this.

In the following case,
```
fn1 <- function()
{
    a <- 2

    fn <- function()
    {
        a <<- 3
    }

    fn()
}

fn1()
```
The following error message is given:
```
"Error in eval(expr, envir, enclos): object 'a' not found\a"
```

**Comment by fong22e** [comment]
Similarly, for cases where there are no existing variables to be found and to be assigned to:

This does not work for the following case where the assignment statement in the nested function is not the last statement:
```
fn3 <- function()
{
    fn <- function()
    {
        d <<- 6
        print(d)
    }

    fn()
}

fn3()
print(d)
```

However, the following case, where the assignment statement is the last statement in the nested function, works just fine.
```
fn4 <- function()
{
    fn <- function()
    {
        e <<- 7
    }

    fn()
}

fn4()
print(e)
```

Strangely, in the cases where there is no nesting, both cases (shown below) work.
```
# assignment statement is the last statement
fn5 <- function()
{
    f <<- 8
}

fn5()
print(f)
```

```
# assignment statement is not the last statement
fn6 <- function()
{
    g <<- 9
    print(g)
}

fn6()
print(g)
```
However the case of `fn6()`, the following warning message is thrown:
```
Warning message:
In .ddg.where(name, parent.env(env)) : Can't find g
```
Yet, this warning message does not show in the case of `fn5()`.

**Comment by blernermhc** [comment]
These all work correctly now.
