### ISSUE TITLE
Support pipes

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#236]
It seems that RDataTracker cannot deal with pipes.

Example code:
```
library(babynames) # data package
library(dplyr)     # provides data manipulating functions.
library(magrittr)  # ceci n'est pas un pipe
library(ggplot2)   # for graphics

babynames %>%
  filter(name %>% substr(1, 3) %>% equals("Ste")) %>%
  group_by(year, sex) %>%
  summarize(total = sum(n)) %>%
  qplot(year, total, color = sex, data = ., geom = "line") %>%
  add(ggtitle('Names starting with "Ste"')) %>%
  print
```

Resulting graph:
![magrittr](https://cloud.githubusercontent.com/assets/1970355/21945675/89d5a6a6-d9aa-11e6-82fd-e1f7f5e524a9.png)

A PDF is generated but not connected to the rest of the graph (it looks the same in DDG-Explorer), most of what is going on is not in the graph.

**Comment by MKLau** [comment]
Yeah, and this looks to be both very useful and highly promoted across the R community

**Comment by MKLau** [comment]
R: "paste("Hello","World!") %>% print()"
magrittr: "Ceci n'est pas une pipe."
RDataTracker: "Il n'y a pas une pipe."

**Comment by erboose** [comment]
Use of the forward pipe (%>%) from the magrittr package has emerged as a powerful new tool in virtually every talk at the RStudio Conference.  Here's the introductory example in the magrittr documentation:

car_data <- 
  mtcars %>%
  subset(hp > 100) %>%
  aggregate(. ~ cyl, data = ., FUN = . %>% mean %>% round(2)) %>%
  transform(kpl = mpg %>% multiply_by(0.4251)) %>%
  print

When this code is run with ddg.run, RDataTracker creates a proper DDG with an operational node for the assignment statement (car_data <- ... print) and an output data node for car_data.  But none of the internal details are captured.

We should explore ways to capture the internal details in statements that use pipes.  One issue will be how to store and display the values passed by pipes from one operation to the next, since these values are implied but not named in the pipe construction.

**Comment by MKLau** [comment]
The tidy folks are discussing a pipe debugging fiction:

https://github.com/tidyverse/magrittr/issues/133#issuecomment-291045163

**Comment by blernermhc** [comment]
Duplicates issue #543
