### ISSUE TITLE
Size 1 vector

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#268]
Looking at the code with Matt, we were not sure what the code with vector size 1 was doing:
https://github.com/End-to-end-provenance/RDataTracker/blob/master/R/RDataTracker.R#L1366

**Comment by blernermhc** [comment]
I think that a common error in R programming is for a variable that the programmer expects to hold a single value to suddenly become a vector.  In reality, R does not have the notion of a single value, but treats that as a vector of length 1.  In order to catch this common programming error, if R indicates that the value is a vector of length 1, we just store in valType  the type of the thing that is in the vector.
```
> a <- 1
> is.vector(a)
[1] TRUE
> class(a)
[1] "numeric"
> length(a)
[1] 1
> b <- c(1, 2)
> is.vector(b)
[1] TRUE
> class(b)
[1] "numeric"
> length(b)
[1] 2
> a <- a + b
> is.vector(a)
[1] TRUE
> class(a)
[1] "numeric"
> length(a)
[1] 2
>
```
So, after the first assignment the valType of a would be "numeric".  After the second assignment to a, it would be "vector(numeric)".

If, instead of a <- a + b, the programmer had done b <- a + b, then there would be no type change to b, as it would be vector(numeric) before and after the assignment.

**Comment by tfjmp** [comment]
That makes sense. Would not that hide some genuine usage of vector? I could imagine scenario where things are added and removed from a vector, and the vector may at some point be of size 1. Maybe @MKLau would have more insight than me.

Maybe recording the size so that whatever is analysing the provenance can detect error, rather than RDataTracker trying to do so. We talked a bit about it last week, separating concerns between capturing the information, and trying to make sense of it.

**Comment by blernermhc** [comment]
That's the problem with dynamically typed languages and with R's eagerness to help, in general.  There will always be legitimate cases. :)

Suddenly having a vector when I was not expecting one has been a source of (really puzzling) bugs for me.  Most notably, we ended up with multiple copies of a ddg in our ddg.txt file because somewhere along the way we thought we were appending a string to the ddg, but we were appending a vector of strings!
 
Elizabeth filled me on the conversation about where the code to check for type coercions should go.  I agree that it should be separated out from RDT.  Think of what she has done on that as a proof of concept.  We can talk tomorrow about where it would be best to put code like that.

**Comment by erboose** [comment]
Yes, that happens all too often and the resulting bug is hard to find.

Another favorite:  If all columns but one are deleted from a data frame, it turns into a vector.

**Comment by MKLau** [comment]
In addition to his RDT is recording the type information, these are good examples. We should turn these into use-cases.

Per Thomas' question, I'm getting the sense that recording the class of the object and then all sub-elements makes sense and might provide enough information to at least highlight the bugs we're taking about. 

So, the val_type would always have the form:

objecttype {elementtype,...} 

I'll put this in the agenda for tomorrow.
