### ISSUE TITLE
RDataTracker produces orphaned nodes in DDG-Explorer

### ISSUE THREAD

**Issue by NullCGT** [End-to-end-provenance/RDataTracker#282]
DDG-Explorer produces strange orphaned nodes unconnected to anything, with labels such as 132-dev.off.132.dev.pdf. When I clicked on it to show the value, it displayed a plot that I had loaded in RStudio but had not cleared from the workspace yet. I think that if there are any plots currently in the workspace, RDataTracker will use them as input for the ddg. Github is not currently allowing me to upload files, but this does not seem to be file specific.

This was mentioned [previously](https://github.com/End-to-end-provenance/RDataTracker/issues/153) but not in its own issue. Matt told me to post this issue here as well as in DDG-Explorer.

**Comment by MKLau** [comment]
Yeah, we've seen this before. It might pay to try and figure out how to address this.

**Comment by blernermhc** [comment]
We probably want a data edge from the last statement to this node, I imagine.  I believe Connor is right, that it represents a graph that was displayed in RStudio when the script ended, so there was no dev.off call.

**Comment by NullCGT** [comment]
This is the R script I generated it with. I was able to reproduce it in several different scripts, however, just by having a graph displayed in RStudio. I don't think the graph necessarily has to even be related.


[Example_0.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1042818/Example_0.txt)

**Comment by erboose** [comment]
Possibly related:  Clicking on the node for an output jpeg file in DDG Explorer and asking how the value was computed returns a graph showing only a single preceding step called "dev.off()".

**Comment by blernermhc** [comment]
That is something else.  In that case, the dev.off function has no input parameters, so there is no data path to trace back.  It would be better if we saw as input the data that was being plotted.  That would require doing something special with plots and recognizing the function call that puts the data into the plot.  Perhaps there are a limited number of such calls so that doing that specialization would make sense.  It would certainly be useful.

I will create a separate issue about this.

**Comment by MKLau** [comment]
@fong22e Let me know if I can help with this.

**Comment by fong22e** [comment]
It seems like this is trickier than we initially thought. Even scripts that do contain `dev.off` produces a ddg that has orphaned nodes. `PlotTest.R` is one such example.

**Comment by MKLau** [comment]
After chatting this morning with @erboose and @blernermhc, it seems that one way to approach this problem is to tackle it package by package. All nodes that are modifying the graphics environment can be nodes that are attached to the output functions, like pdf, png, jpeg, tiff, etc.  dev.off is also attached to the output function node as well.

**Comment by tfjmp** [comment]
That sounds like a good plan.

**Comment by blernermhc** [comment]
This is fixed.
