### ISSUE TITLE
Problems with file and url nodes

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#336]
The current version of RDataTracker does not always create file and url nodes correctly when a script reads from or writes to a connection created with the "file" or "url" commands.  For an example, see the attached json files (renamed as .txt for Github) created with the development and summary branches for the following script:

set.seed("12345")
file.in <- url("http://harvardforest.fas.harvard.edu/sites/harvardforest.fas.harvard.edu/files/weather/metsta.dat")
df <- readLines(file.in, warn=FALSE)
file.out <- file("test.dat", "w")
writeLines(df, file.out)

The summary branch tries to address these and related problems by (1) removing "file" from the list of functions that read files, (2) adding "writeLines" to the list of functions that write files, (3) for connections, creating a file or url node using the connection description, if possible, (4) for connections, replacing the connection number with the connection description as the value of the connection in the ddg, and (5) saving a snapshot of all the data read from a url, regardless of the value of max.snapshot.size (the last for reproducibility).

This seems to be an improvement but still doesn't do everything we want.  For example, if R decides to close a connection, as it sometimes does without an explicit "close" command, the variable that holds the name of the connection persists but it no longer points to anything, so the attributes of the connection are no longer available and the connection description cannot be used to create a node.  This appears to happen in HFDatasetPreview.R, where URL nodes are not created where they should be.

A summary file for the above script is also attached.
[ddg-development-branch.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1134104/ddg-development-branch.txt)
[ddg-summary-branch.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1134105/ddg-summary-branch.txt)
[ddg-summary.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1134106/ddg-summary.txt)

**Comment by erboose** [comment]
One possible solution might be to create a lookup table of connections as a script executes so the necessary information could be found there if a connection is closed (destroyed).

**Comment by blernermhc** [comment]
I am working on this.  I agree that the right approach is to create a table of connections.

**Comment by blernermhc** [comment]
How does this look for a ddg for the example above?  There is asymmetry in that the url/file is used as input to the url/file function on read operations, but on write operations it shows up as being written to when the writeLines happens.

The more symmetric alternatives would be:

1. To have the file be input to the file function even when the connection is being created to write to, or
2. To have the url be input to the readLines function, rather than to the file function.

My reasoning for doing it as I have is that what we logically want to capture is flow from input to output.  So, have a url/file node at the earliest reference when it is opened for reading, and at its latest reference when it is for writing.

But what if there are multiple calls to write to a file, writing one line at a time for example?  Maybe we should have the file node when the connection is closed, or at the end of the execution if it is never explicitly closed?  Or search back for the last write if it not explicitly closed?

Also, currently, if you right click on the data node for a connection, you get something that is not very helpful.  I want to change it to say something like "read connection for http://...".


<img width="450" alt="image" src="https://user-images.githubusercontent.com/5429878/34622327-be56d696-f21a-11e7-9262-b492849151f4.png">

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/4498f5208a1dfb60bfd2df2ad3b17e8cbe4657f2
