### ISSUE TITLE
Eliminate ddg.txt

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#343]
We should just use ddg.json

- Need to change ddg.display to send the json file
- Can eliminate the writing of the ddg.txt file
- Clean up the test files

Possibly more to do...

**Comment by NullCGT** [comment]
In addition to the other things about ddg.txt, I've definitely been having issues with loading DDGs from the .txt file. Loading using ddg.display results in the data nodes being orphaned and having no edges connected to the graph. I don't know if this is due to changes I made or only on my branch, but using ddg.json instead would probably help.

**Comment by blernermhc** [comment]
Done in f62b3cd
