### ISSUE TITLE
ddg when the script is empty

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#387]
What should the ddg be if the user passes in a file to `ddg.run`, but it is empty (does not contain any lines of code)? Currently, RDataTracker throws the following error:
```
Error in eval(substitute(select), nl, parent.frame()) : 
  object 'ddg.hash' not found 
```

**Comment by fong22e** [comment]
This also happens if the script contains a constant. For example, if the script just contains `5` or `"a"`.

**Comment by blernermhc** [comment]
It certainly should not report an error message.  In the case of it being empty, it should just contain the environment node.  Not sure about the case where it contains just an expression.  I suppose it should contain a single procedural node.

This is low priority since we would not expect RDT to be used in those cases.

**Comment by blernermhc** [comment]
prov.json is generated correctly now.
