### ISSUE TITLE
Incorrect line number information

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#472]
Line number information is not always correct.  Oddly, at least in this case, it works correctly from RStudio, but not from the ant test script.

Here is output in RStudio.  This is displaying starting and ending line and column numbers for each statement in DataTypeTest.R.  In RStudio, these values are correct.

> prov.run("DataTypeTest.R", annotate=T, max.loops=1, snap=10)
[1] "pos = 5 1 5 14"
[1] "pos = 7 1 7 27"
[1] "pos = 9 1 9 1493"
[1] "pos = 11 1 11 17"
[1] "pos = 13 1 13 10"
[1] "pos = 15 1 15 14"
[1] "pos = 17 1 17 20"
[1] "pos = 19 1 19 22"
[1] "pos = 21 1 21 20"
[1] "pos = 23 1 23 64"
[1] "pos = 25 1 25 63"
[1] "pos = 28 1 28 27"
[1] "pos = 29 1 29 43"
[1] "pos = 30 1 30 40"
[1] "pos = 35 1 35 37"
[1] "pos = 38 1 38 55"
[1] "pos = 39 1 39 55"
[1] "pos = 42 1 42 79"
[1] "pos = 43 1 43 98"
[1] "pos = 46 1 46 60"
[1] "pos = 47 1 47 92"
[1] "pos = 48 1 48 33"

But when run from the ant test script, using the RecordedValue branch, the locations start correct but then become first incorrect and then NA.  Also, line 48 is the line containing the last statement in the file.

     [exec] < [1] "pos = 5 1 5 14"
     [exec] < [1] "pos = 7 1 7 27"
     [exec] < [1] "pos = 9 1 9 1493"
     [exec] < [1] "pos = 11 1 11 17"
     [exec] < [1] "pos = 13 1 13 10"
     [exec] < [1] "pos = 15 1 15 14"
     [exec] < [1] "pos = 17 1 17 20"
     [exec] < [1] "pos = 19 1 19 22"
     [exec] < [1] "pos = 21 1 21 20"
     [exec] < [1] "pos = 23 1 23 64"
     [exec] < [1] "pos = 25 1 25 63"
     [exec] < [1] "pos = 48 1 48 33"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"
     [exec] < [1] "pos = NA NA NA NA"

The values are wrong in the expected results, too, (which would have come from the development branch) but different:

Instead of the correct 28, it has 43.
Instead of 29, it has 44
And then they are all NA after that

**Comment by blernermhc** [comment]
This is really baffling.  util::getParseData is returning incorrect information.  I don't understand why it would behave differently in RStudio compared to our ant scripts.

Taking this off the CRAN Release milestone as it seems to work from RStudio.

**Comment by fong22e** [comment]
I noticed a few things as I was updating the tests:

**FunctionAnnotation (rdt and rdtLite)**
* Line and column numbers for and after lines related to defining a special operator are incorrect.
* Everything prior to that is correct.

**Plot1, NoDevOff (rdt and rdtLite)**
* I noticed that line and row numbers seem to correspond to a plotting function (or line of code) other than itself. This may be due to how plotting is done in R. There is no such issue in Plot2 and Plot3.
* e.g. The row and column number for the line `title("RStudio display")` is the row and column number for `mpg = c(mean(cars4Cyl.df$mpg), mean(cars6Cyl.df$mpg), mean(cars8Cyl.df$mpg))`
* e.g. The row and column number for the line `x <- 1` is the row and column number for the line above it, `plot(cylinders, mpg)`
* e.g. The row and column number for the line `plot(cylinders, mpg)` is the row and column number for the line below it, `title("RStudio display")`.

**Comment by blernermhc** [comment]
Thanks for examining the test results so carefully!

These problems are all related to the use of =, rather than <- to do assignment, and so is redundant with issue #411 .  I verified this by replacing the = with <- in the test cases, and after doing this the line numbers came out correctly.  I have not changed the test cases on github, though, as we will then know when this problem gets fixed.  The R folks have acknowledge that this is an R bug.
