### ISSUE TITLE
provR and .ddg.start

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#490]
Today I merged master and development into my branch, provRtests. I tried running tests in RStudio and it gave me this error:
```
Error in .ddg.start("get.data") : could not find function ".ddg.start"
In addition: Warning message:
In .ddg.where(name, parent.env(env), warning) : Can't find .ddg.start
```
Did something get lost in the merge?

**Comment by blernermhc** [comment]
Yes, it looks like these updates got lost.  I see a commit on August 4, where the changes have been made.  This is coming from DailySolarRadiation, right?

I think what happened is that we had moved the ant tests to the scriptTests folder and started using the tests folder for testthat.  The changes to the scripts were done on a branch that had the scripts still in the tests folder, though.  So, it seems like when the merge occurred to combine those changes, the script changes were lost.  git doesn't really understand moving files, I don't think.

I don't understand why we were not seeing Travis errors, though, since this seems to have been a problem on dev since August 8...

**Comment by blernermhc** [comment]
I think I understand why we do not see the errors when we test.  Here is what I have observed in RStudio:
1.  If you load DailySolarRadiation.R and source it (without RDT or provR loaded), you get the .ddg.stat error.
2. If you then load RDataTracker and *source* DailySolarRadiation.R, you will get the same error.
3. If you use prov.run, you do not get the error.

I think the issue is that when we actually evaluate the R statement, we are doing that inside the RDataTracker namespace, and so .ddg.start is visible.

Not sure what the right solution is....  Obviously, we should update the scriptTests again to remove any calls to ddg functions.  I am tempted to not bother doing anything else, though.  There is no reason anybody should want to call .ddg functions from their code.  I suppose we could look for those calls, but it is not clear to me that it would be worth the effort.

**Comment by fong22e** [comment]
Yes, it is from DailySolarRadiation. What functions should I call instead of .ddg.start and .ddg.save? Is it prov.init and prov.save?

**Comment by blernermhc** [comment]
You should just remove calls to .ddg.start and .ddg.finish.  There is no equivalent in the current API.
