### ISSUE TITLE
provR and RMarkdown

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#492]
When running the test RMarkdown using provR, this error is thrown:
```
Error in .ddg.start("ddg.chunk_1") : could not find function ".ddg.start"
In addition: Warning message:
In .ddg.where(name, parent.env(env), warning) : Can't find .ddg.start
```
On further investigation, this is due to `.ddg.start` and `.ddg.finish` added to surround code chunks before executing the rmd file. This code is in RDataTracker_core.R. Strangely, no such error is reported when the test is run using RDataTracker.

Since both functions are no longer in use, what should I use to mark code chunks instead of using `.ddg.start` and `.ddg.finish`?

**Comment by blernermhc** [comment]
This is a little interesting.  The .Rmd file does not contain the calls to .ddg.start.  They are added by .ddg.markdown, which is called from .ddg.init.

There is no error in RDataTracker because .ddg.start and .ddg.finish are defined in Annotation_rdt.R.  They are not defined in Annotation_prov.R.

I can imagine a couple of directions we can go on this:
1. Move .ddg.start and .ddg.finish to Annotation_core.R so it is visible to both tools.
2. Modify the .ddg.markdown code, or where it is called, so that it only executes in RDataTracker.
3. Disable the RMarkdown code in both tools.

I have a slight preference for #1, but could go with any of these solutions.

**Comment by fong22e** [comment]
I could definitely implement the first option if that is the best.

**Comment by blernermhc** [comment]
Let's do that.

**Comment by blernermhc** [comment]
Actually, on second thought, the way that RMarkdown is handled involves annotation, which we don't want to do in the rdtLite version.  I think #2 would be the better solution.

**Comment by blernermhc** [comment]
Wavering again...  Maybe better to just run the markdown as a normal R script without adding the start...finish.  @erboose, what do you think?

**Comment by blernermhc** [comment]
Changed so that in rdtLite we get provenance without start and finish nodes.

Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/10970437c0749d065c735d8a3c2e684c8d4e92e0
