### ISSUE TITLE
Warning nodes that sometimes do not show

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#603]
In the following case, I get a warning thrown, but there are no warning nodes in the json. This occurs both in `rdtLite` and `rdt`, in basic test.
```
tryCatch (
    does.not.exist(),
    error = function(e) {}
)
```
```
Warning message:
In .ddg.where(name, parent.env(env), warning) : Can't find does.not.exist
```

After testing it more, I found that the warning becomes an error in this case (with an error node):
```
tryCatch (
    does.not.exist()
)
```
And in this case, there is a warning node:
```
tryCatch (
    warning("a warning"),
    error = function(e) {}
)
```

**Comment by blernermhc** [comment]
I think the only problem is that .ddg.where is throwing a warning in your first example.  It shouldn't do that.

If you run the first code without collecting provenance, you will see that R does not produce an error because it is swallowed up by the exception handler.  That is the behavior we should also see if run with provenance collection.  The warning is that rdtLite is confused, not that the R code generated a warning.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/pull/645/commits/65a385f2f0973c863fcbb2a0e68b734334eed3cc
